snuhcs-course/swpp-2023-project-team-12

.github/workflows/android-lint.yml
android/RunUsAndroid/app/build.gradle
android/RunUsAndroid/app/config/checkstyle/google_checks.xml

- android-lint 파일에서 gradlew 찾는 경로 변경
- root directory는 swpp-... 인데 gradlew 파일은 swpp-2023-project-team-12/android/RunUsAndroid/에 있어서 경로를 찾지 못해 CI 터지는 문제 default directory 설정으로 해결
- checkstyle에 터지는 파일 너무 많아서 우선 disable 함
- checkstyle 설정

[CI] Update path to find gradlew

---

.github/workflows/android-lint.yml
android/RunUsAndroid/app/build.gradle
android/RunUsAndroid/app/config/checkstyle/google_checks.xml

#16 config setting 초기화된 상태로 들어간 커밋 author 변경
- 코드 변경 사항 없음

Change author of commits of PR #16

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java

Immediate update of location didn't work
Immediate update upon fragment start
Moved  some codees in onCreateView -> onResume
---
expected.
---

Debug: single mode immediate location update onResume

---

android/RunUsAndroid/app/src/main/res/layout/activity_login.xml

Minor: 비밀번호 입력 시 텍스트 별(*)로 표시 

---

android/RunUsAndroid/app/build.gradle
android/RunUsAndroid/app/src/androidTest/java/com/example/runusandroid/GenderRadioButtonUiTest.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/RetrofitClient.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/SignUpStep4Activity.java
android/RunUsAndroid/app/src/main/res/layout/activity_sign_up_step4.xml

None
None
reviewer.
---
expected.
---

Feat & Styling: 성별 입력 라디오 버튼으로 받기 

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/HistoryApi.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/HistoryDataforRendering.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/RetrofitClient.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/history/HistoryFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java
android/RunUsAndroid/app/src/main/res/layout/fragment_history.xml
django/history/serializers.py
django/history/urls.py
django/history/views.py
django/runusDjango/settings.py

Feat: 히스토리 페이지에서 히스토리 보여주기 

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java
android/RunUsAndroid/app/src/main/res/values/strings.xml

폰트 고치다 참패해서 겸사겸사 한 마이너 문구 수정 따로 PR 올릴게요 ㅠ

Styling: Edit navigation to korean

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModePlayFragment.java

fix typo
reviewer.
---
expected.
---

Fix: minor fix

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/history/HistoryFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/home/HomeFragment.java

거리: 소수점 2자리
칼로리: 소수점 1자리
reviewer.
---
expected.
---

Styling: Edit NumberFormatting of distance in home and history Fragment

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java

- [V] Added new feature(s)
reviewer.
---
expected.
---

Singlemode nav bar fix

---

android/RunUsAndroid/app/build.gradle
android/RunUsAndroid/app/src/main/AndroidManifest.xml
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/BackGroundLocationService.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java
android/RunUsAndroid/app/src/main/res/layout/dialog_mission_start.xml

백그라운드에서 위치가 수집되지 않아 포그라운드로 돌아왔을 때 기존 위치와 비교해 직선거리로 나타내던 현상 제거
백그라운드 정보를 수집하게 되면서, 위치를 항상 허용으로 설정해야 백그라운드에서 동작합니다!
- [V] Added new feature(s)
reviewer.
---
expected.
---

Add: Background GPS service

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ActivityRecognition/UserActivityBroadcastReceiver.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/MainActivity2.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModePlayFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java
android/RunUsAndroid/app/src/main/res/layout/fragment_multi_room_play.xml
android/RunUsAndroid/app/src/main/res/layout/fragment_single_mode.xml

activity recognition이 제대로 작동하지 않는 현상
- 코드 변경사항이 없는데 activity recognition이 다시 작동하지 않아서, 일단 시작시의 isRunning default value를 true로 설정했습니다. 
- 별개로 싱글모드 및 멀티모드 플레이 시 우측하단의 보이지 않는 버튼을 누르면 토스트로 마지막으로 관측된 activityType, transitionType, isRunning 값을 보여주도록 설정했습니다
- [ v] Fixed identified bug(s)
reviewer.
---
expected.
---

Fix: Hidden button activity recog

---

django/account/tests.py
django/history/tests.py

CI 살리는중.. 

---

android/RunUsAndroid/app/build.gradle
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/HistoryDataforRendering.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/history/HistoryFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/home/HomeFragment.java
android/RunUsAndroid/app/src/main/res/drawable/marker_default.xml
android/RunUsAndroid/app/src/main/res/drawable/marker_selected.xml
android/RunUsAndroid/app/src/main/res/drawable/round_shape_for_daily_history.xml
android/RunUsAndroid/app/src/main/res/drawable/round_shape_for_monthly_history.xml
android/RunUsAndroid/app/src/main/res/layout/fragment_history.xml
android/RunUsAndroid/app/src/main/res/layout/fragment_home.xml
android/RunUsAndroid/settings.gradle
django/history/serializers.py
django/history/views.py

Feat: 히스토리 페이지 성능 개선 및 스타일링

---

android/RunUsAndroid/app/build.gradle
android/RunUsAndroid/app/src/main/res/drawable/round_strokegreen_shape.xml
android/RunUsAndroid/app/src/main/res/layout/fragment_user_setting.xml

Styling: UserSettingFragment

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModeFragment.java
android/RunUsAndroid/app/src/main/res/layout/create_room_modal_layout.xml

Styling: RoomCreateDialog

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModeWaitFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/SocketListenerThread.java

https://github.com/snuhcs-course/swpp-2023-project-team-12/issues/64
앱이 백그라운드에 있을 때 게임 시작 시 유저를 방에서 내보내도록 수정
준비 버튼을 추가하고 앱이 백그라운드에서 실행될 땐 준비를 취소하는 식으로 구현해도 될 것 같습니다.
---
expected.
---

Fix: 앱이 백그라운드에 있을 때 게임 시작 시 발생하는 버그 수정

---

android/RunUsAndroid/.gitignore
android/RunUsAndroid/app/src/main/res/values/themes.xml

매번 폰트설정하기 귀찮아죽겠다
editText, button, Textview에는 자동으로 폰트적용됨 (별도로 선언하면 그게 우선시되고, bold 등은 따로 설정해야됨)
AppcompatEditText, AppcompatButton, TimePicker, NumberPicker, CalenderView 등에는 아직 작동 확인되지 않음
reviewer.
---
expected.
---

default font set for editText, button, Textview

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/history/HistoryFragment.java
android/RunUsAndroid/app/src/main/res/layout/fragment_history.xml

상단 월 기록 삭제 
reviewer.
---
expected.
---

Refactor: Refactor HistoryFragment UI

---

android/RunUsAndroid/app/src/main/java/MultiMode/MultiModeUser.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModeWaitFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/SocketListenerThread.java
android/RunUsAndroid/app/src/main/res/drawable/multi_room_waiting_list_background.xml
android/RunUsAndroid/app/src/main/res/drawable/round_strokegreen_backwhite.xml
android/RunUsAndroid/app/src/main/res/layout/fragment_multi_room_wait.xml
android/RunUsAndroid/app/src/main/res/layout/waiting_user_item.xml
android/RunUsAndroid/app/src/main/res/values/themes.xml

1. 멀티 모드 스타일링
2. 탑바 색 흰색으로 변경
reviewer.
---
expected.
---

Styling: Polish multi mode waiting room

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModeWaitFragment.java

멀티모드 wait room 디자인 변경 뒤 시작시간이 제대로 표시되지 않는 버그 (코드가 사라져있었음)
해당 버그 수정
reviewer.
---
expected.
---

Fix: multimode wait fragment start time textview

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/AccountAPIFactory.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/AccountApi.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/LoginActivity.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/MainActivity2.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/RefreshTokenData.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/RetrofitClient.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModePlayFragment.java
django/account/models.py
django/account/urls.py
django/account/views.py

(https://github.com/snuhcs-course/swpp-2023-project-team-12/issues/74)
+ jwt 인증 관련 버그로 장고 서버에서 발생하는 401 error 수정 (멀티모드 게임 안 끝나는 버그, 로그인 안되는 버그, 유저 정보 못 불러오는 버그 등 장고 method와 관련된 버그)
+ 회원가입 관련 버그 수정 (create_user 함수에 exp가 argument로 들어가있어서 삭제)
reviewer.
---
expected.
---

Fix: jwt 인증 관련 버그 수정

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ActivityRecognition/RunningState.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ActivityRecognition/UserActivityBroadcastReceiver.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/MainActivity2.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/PermissionSupport.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModePlayFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/user_setting/UserSettingFragment.java

activity transition이 제대로 관측되지 않는 현상
fixed
reviewer.
---
expected.
---

Fix activity recog

---

android/SocketServer/src/MultiMode/MultiModeRoom.java
android/SocketServer/src/MultiMode/RoomManager.java
android/SocketServer/src/MultiMode/RoomObserver.java
android/SocketServer/src/Server.java

옵저버 패턴 적용하여 수정합니다.
reviewer.
---
expected.
---

Fix: apply observer pattern

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/BackGroundLocationService.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java

네비게이션바 빠르게 전환시 종료되는 현상
backgroundLocationService를 등록하고 해제하는 과정이 async로 진행되었기 때문에 등록이 완료되기 전 종료가 호출되었을 경우 nullpointException 발생
-> nullcheck 추가
reviewer.
---
expected.
---

fix: fast navigation change

---

android/RunUsAndroid/app/src/main/AndroidManifest.xml

Minor: Block landscape

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModeAdapter.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModeFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModePlayFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModeWaitFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/SocketListenerThread.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/SocketManager.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/user_setting/UserSettingFragment.java
android/SocketServer/src/Server.java

Hotfix : 멀티모드에서 다른 아이디로 재로그인해도 UI에 기존 로그인 정보가 뜨는 문제 수정

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModePlayFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeResultFragment.java

봉천역 기준 신림-서울대입구역까지 다보임
걷거나 뛰어도 지도 범위가 너무 커서 라인이 안보여 조정함

지도 사이즈 재조정

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ActivityRecognition/UserActivityBroadcastReceiver.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ExpSystem.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/LoginActivity.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/SignUpStep3Activity.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModePlayFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeResultFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/user_setting/UserSettingFragment.java

Disable toasts for testing 
Disable toasts for testing 
reviewer.
---
expected.
---

Fix: Disable toasts

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModePlayFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeResultFragment.java

싱글모드  경기 후 상세기록 클릭시 앱 다운되는 문제 존재하여 해결하였습니다. 
싱글모드, 멀티모드에서 경기 종료시 경험치 획득 토스트 추가하였습니다. 
reviewer.
---
expected.
---

Hotfix: 싱글모드 상세기록 에러 수정 및 경험치 획득 토스트 추가

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/MainActivity2.java

초기 권한설정 시 전부 allow 해도 "2회 물어봤음에도 권한이 거절된 경우" 의 dialog가 떠있는 현상
#129 에 의해 발생한 버그, location 권한이 없는데 initial location을 request 했음
-> 권한이 있을 시에만 mainActivity2 생성 시 request 하도록 수정
reviewer.
---
expected.
---

hotfix: permission dialog

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/FindIdActivity.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/LoginActivity.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/MainActivity2.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ResetPasswordActivity1.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ResetPasswordActivity2.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/SignUpStep1Activity.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/SignUpStep2Activity.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/SignUpStep3Activity.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/multi_mode/MultiModeFragment.java
android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java

edittext 활성화 후 키보드 외 영역 터치 시 키보드 없어지도록 fix
edittext 활성화 후 키보드 외 영역 터치 시 키보드 없어지도록 fix
reviewer.
---
expected.
---

Hotfix: Hide keyboard

---

android/RunUsAndroid/app/src/main/java/com/example/runusandroid/ui/single_mode/SingleModeFragment.java

- [ㅍ] Minor Update
reviewer.
---
expected.
---

Minor : remove some debug messages
